// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA5HZSZq3Jl92aVSLJLE3dA2qdpQAfWXks',
    appId: '1:1097998256478:web:f03178efbf97ea15c5e7cf',
    messagingSenderId: '1097998256478',
    projectId: 'dev-mate-ce028',
    authDomain: 'dev-mate-ce028.firebaseapp.com',
    storageBucket: 'dev-mate-ce028.firebasestorage.app',
    measurementId: 'G-88EWWG9RZL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBmiSCJGPxBcAxEwMIcktHMvyw_ri3pJcI',
    appId: '1:1097998256478:android:7fe307fc4258ab47c5e7cf',
    messagingSenderId: '1097998256478',
    projectId: 'dev-mate-ce028',
    storageBucket: 'dev-mate-ce028.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCsj5xxfDmSvZY2ekcJ7gpqvyPtXAIlJR0',
    appId: '1:1097998256478:ios:023844ac09e557f5c5e7cf',
    messagingSenderId: '1097998256478',
    projectId: 'dev-mate-ce028',
    storageBucket: 'dev-mate-ce028.firebasestorage.app',
    iosBundleId: 'com.example.devMate',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCsj5xxfDmSvZY2ekcJ7gpqvyPtXAIlJR0',
    appId: '1:1097998256478:ios:023844ac09e557f5c5e7cf',
    messagingSenderId: '1097998256478',
    projectId: 'dev-mate-ce028',
    storageBucket: 'dev-mate-ce028.firebasestorage.app',
    iosBundleId: 'com.example.devMate',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA5HZSZq3Jl92aVSLJLE3dA2qdpQAfWXks',
    appId: '1:1097998256478:web:d3e62dcd111fe5cec5e7cf',
    messagingSenderId: '1097998256478',
    projectId: 'dev-mate-ce028',
    authDomain: 'dev-mate-ce028.firebaseapp.com',
    storageBucket: 'dev-mate-ce028.firebasestorage.app',
    measurementId: 'G-YQ91VNFCM1',
  );
}
